### ISSUE TITLE
Fails to render without error if name is a list

### ISSUE THREAD

**Issue by filcuk** [zwpaper/obsidian-progressbar#10]
Following name will simply not show anything in preview/read mode:
```progressbar
name: - Progress
width: 50%
value: 10
max: 25
```
As opposed to something like this, which results in an error:
```progressbar
name: # Progress
width: 50%
value: 10
max: 25
```

This is a nice plugin, I wish I was able to add the bar to headings or lists, but I understand there may be limitations.

**Comment by zwpaper** [comment]
it seems not able to be implemented, sorry.
