### ISSUE TITLE
The template does not work

### ISSUE THREAD

**Issue by yinlokc** [zwpaper/obsidian-progressbar#12]
<img width="781" alt="image" src="https://github.com/zwpaper/obsidian-progressbar/assets/2225622/5b9bde5f-63f9-402f-b58c-69e348d5a756">

**Comment by zwpaper** [comment]
funny, let me have a look at this

**Comment by zwpaper** [comment]
the 0.4.0 is not yet update to market, let me fire a PR to fix this

**Comment by zwpaper** [comment]
fixed by https://github.com/zwpaper/obsidian-progressbar/releases/tag/0.5.0
