### ISSUE TITLE
Request to be able to have options to have buttons for making increment or decrements in the kind: manual

### ISSUE THREAD

**Issue by sukumar1210** [zwpaper/obsidian-progressbar#13]
I think it would be useful to have buttons to increase or decrease the value in the kind: manual as this would be more convenient instead of editing the written value in the document.
more like:
![image](https://github.com/zwpaper/obsidian-progressbar/assets/73037127/84dc2f57-4111-4f1b-94da-fa63aaf39f32)

**Comment by sukumar1210** [comment]
i have this almost complete, @zwpaper can u assign this issue to me?

**Comment by zwpaper** [comment]
Hi @sukumar1210, thanks so much for raising this and the PR.

we would mostly use one PR for one function for fix.

and sorry for not getting what you mean by saying `making indents "not a problem"`, can you remind me with more details?

**Comment by sukumar1210** [comment]
> and sorry for not getting what you mean by saying making indents "not a problem", can you remind me with more details?

I have created an issue explaining the issue at #15
