### ISSUE TITLE
I think having a custom progress bar with a start and end date would be pretty cool.

### ISSUE THREAD

**Issue by zwpaper** [zwpaper/obsidian-progressbar#7]
I think having a custom progress bar with a start and end date would be pretty cool. 

People in school can use it to countdown semesters or school years instead of using a calendar year.

_Originally posted by @MatthewLeboffe in https://github.com/zwpaper/obsidian-progressbar/discussions/5_

**Comment by sukumar1210** [comment]
hey @zwpaper , Mind if i work on this? and by this i mean this issue and others if i could. I was looking for some projects that i can use to build some confidence on contributing on open-source, i am a bit hesitant towards very big repositories so i find this very fitting and i feel like i can contribute to it too based on my skill-set.

Although i would want to know if you still maintain this repo and if my PR will be accepted if i decide to work on this. I can work on it along with you if it came to enhancements.

**Comment by zwpaper** [comment]
Hi @sukumar1210, feel free to start the works, I started this project with my little frontend experience, it may be a easy start for you if you were interested in.

I would definitely like to maintain this project because I was the user, and I would be appreciated and happy to help if you would like to help maintain this

**Comment by zwpaper** [comment]
fixed by https://github.com/zwpaper/obsidian-progressbar/releases/tag/0.5.0
